name: Release on push to master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOKCER_GITHUB_KEY }}
          DOCKER_REGISTRY_URL: "docker.pkg.github.com"
      - uses: actions/docker/cli@master
        args: "build -t docker.pkg.github.com/gerred/docker-release-action/app:1.0"
      - uses: actions/docker/cli@master
        args: "push docker.pkg.github.com/gerred/docker-release-action/app:1.0.0"
